# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: "semiannually"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: "semiannually"
    groups:
      python:
        patterns:
          - "requirements.*"
    cooldown:
      default-days: 7